### ISSUE TITLE
[FEAT] Add image builds for nightly branch

### ISSUE THREAD

**Issue by chancez** [linuxserver/docker-plex-meta-manager#12]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

plex-meta-manager has an nightly branch where new features get added first. Having an image tag that follows nightly could be useful to test new features without having to build it yourself.

### Reason for change

Currently I'm testing a new feature in plex-meta-manager and I use the linuxserver image, but have to build it myself to use nightly.

**Comment by thespad** [comment]
This should now be live.
